#!/usr/bin/env python3
"""
gen_dalet_vectors.py - DaletOption vectors from the funding bond reference.

Reads PERP/reference/fundingbond/vectors.json (the standard, computed by model.py at 60 digits)
and emits test/DaletOptionVectors.gen.sol: every dalet_price vector, the p_atm vector (the put at
S = K = 1), the D vectors, and the vectors on which the pricer must revert.

Run:  python3 script/gen_dalet_vectors.py [path/to/vectors.json]
Out:  test/DaletOptionVectors.gen.sol  (committed; regenerate when vectors.json changes)

Standard library only. British English.
"""
import json
import os
import sys
from decimal import Decimal

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT = os.path.join(HERE, "..", "..", "..", "PERP", "reference", "fundingbond", "vectors.json")
OUT = os.path.join(HERE, "..", "test", "DaletOptionVectors.gen.sol")

# Vectors the model prices but a WAD implementation must refuse, with the error it raises.
WAD_REVERTS = {"edge/zero_scale": "ZeroScale"}
MODEL_REVERTS = {"edge/negative_parity_leg": "NegativeParityLeg"}


def wad(x):
    v = Decimal(x).scaleb(18)
    assert v == v.to_integral_value(), x
    return int(v)


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else DEFAULT
    with open(src) as fh:
        doc = json.load(fh)
    prices, dvecs, reverts = [], [], []
    for v in doc["vectors"]:
        vid = v["id"]
        if v["fn"] == "dalet_price":
            args = [wad(a) for a in v["args"]]
            if vid in WAD_REVERTS or vid in MODEL_REVERTS:
                reverts.append((vid, args, WAD_REVERTS.get(vid) or MODEL_REVERTS[vid]))
                continue
            o = v["outputs"]
            fc = [int(o[k]["wad"][b]) for k in ("call", "put", "delta_call", "delta_put")
                  for b in ("floor", "ceil")]
            prices.append((vid, args, fc, o["call"]["exact"], o["put"]["exact"]))
        elif v["fn"] == "p_atm":
            sigma, h = (wad(a) for a in v["args"])
            o = v["outputs"]["value"]["wad"]
            # the put at S = K = 1 is p_atm; the call equals it by parity (r = 0)
            fc = [int(o["floor"]), int(o["ceil"])] * 2 + [0, 0, 0, 0]
            prices.append((vid, [10 ** 18, 10 ** 18, h, 0, sigma], fc,
                           v["outputs"]["value"]["exact"], v["outputs"]["value"]["exact"]))
        elif v["fn"] == "D":
            o = v["outputs"]["value"]["wad"]
            dvecs.append((vid, wad(v["args"][0]), int(o["floor"]), int(o["ceil"])))

    L = []
    L.append("// SPDX-License-Identifier: UNLICENSED")
    L.append("pragma solidity ^0.8.31;")
    L.append("")
    L.append("// AUTO-GENERATED by script/gen_dalet_vectors.py - do not edit by hand.")
    L.append("// Source: PERP/reference/fundingbond/vectors.json (model.py, 60 digits).")
    L.append("// All values WAD (1e18). fc: call, put, delta_call, delta_put, each floor then ceil")
    L.append("// of the exact value; for p_atm the deltas are not checked (zero).")
    L.append("")
    L.append("struct PriceVector {")
    L.append("    string id;")
    L.append("    uint256 S;")
    L.append("    uint256 K;")
    L.append("    uint256 T;")
    L.append("    uint256 r;")
    L.append("    uint256 sigma;")
    L.append("    uint256[8] fc;")
    L.append("}")
    L.append("")
    L.append("struct CdfVector {")
    L.append("    string id;")
    L.append("    int256 x;")
    L.append("    uint256 floor;")
    L.append("    uint256 ceil;")
    L.append("}")
    L.append("")
    L.append("struct RevertVector {")
    L.append("    string id;")
    L.append("    uint256 S;")
    L.append("    uint256 K;")
    L.append("    uint256 T;")
    L.append("    uint256 r;")
    L.append("    uint256 sigma;")
    L.append("    bytes4 selector;")
    L.append("}")
    L.append("")
    L.append("library DaletOptionVectors {")
    L.append("")
    L.append("    function prices() internal pure returns (PriceVector[] memory v) {")
    L.append("        v = new PriceVector[](%d);" % len(prices))
    for i, (vid, a, fc, ce, pe) in enumerate(prices):
        L.append("        // call %s  put %s" % (ce, pe))
        L.append('        v[%d] = PriceVector("%s", %s, [%s]);'
                 % (i, vid, ", ".join(str(x) for x in a),
                    ", ".join("uint256(%d)" % fc[0] if j == 0 else str(x)
                              for j, x in enumerate(fc))))
    L.append("    }")
    L.append("")
    L.append("    function cdf() internal pure returns (CdfVector[] memory v) {")
    L.append("        v = new CdfVector[](%d);" % len(dvecs))
    for i, (vid, x, f, c) in enumerate(dvecs):
        L.append('        v[%d] = CdfVector("%s", %d, %d, %d);' % (i, vid, x, f, c))
    L.append("    }")
    L.append("")
    L.append("    function reverts(bytes4[2] memory sel) internal pure returns (RevertVector[] memory v) {")
    L.append("        // sel: [ZeroScale, NegativeParityLeg]")
    L.append("        v = new RevertVector[](%d);" % len(reverts))
    for i, (vid, a, err) in enumerate(reverts):
        L.append('        v[%d] = RevertVector("%s", %s, sel[%d]);'
                 % (i, vid, ", ".join(str(x) for x in a), 0 if err == "ZeroScale" else 1))
    L.append("    }")
    L.append("}")
    L.append("")
    with open(OUT, "w") as fh:
        fh.write("\n".join(L))
    print("%d price, %d cdf, %d revert vectors -> %s" % (len(prices), len(dvecs), len(reverts),
                                                          os.path.relpath(OUT)))


if __name__ == "__main__":
    main()
