#!/usr/bin/env python3
"""
gen_vectors.py - Reference vector generator for the TMath test suite.

Computes reference values for exp, ln, sqrt, sin, cos at 50-digit precision
using mpmath, then emits a Solidity file (TMathVectors.gen.sol) containing the
vectors as hardcoded arrays for Foundry to assert against.

Run:  python3 gen_vectors.py
Out:  TMathVectors.gen.sol  (committed; regenerate only when the input set changes)

All values are 1e18-scaled (WAD), matching the TMath library convention.
British English, no em dashes.
"""

from mpmath import mp, mpf, exp, log, sqrt, sin, cos, pi, floor

mp.dps = 50  # 50 decimal digits of working precision

WAD = mpf(10) ** 18


def to_wad(x):
    """Convert an mpf real to a 1e18-scaled integer, truncating toward zero
    to match the EVM's integer arithmetic."""
    scaled = x * WAD
    # Truncate toward zero (matches Yul div/sdiv on the final result).
    return int(scaled) if scaled >= 0 else -int(-scaled)


# ----------------------------------------------------------------------
# Input sets. Chosen to exercise: small values, values near 1, large
# values, branch boundaries, and the domain edges of each function.
# ----------------------------------------------------------------------

# exp: domain is (0, 61e18]. Test positive exponents; the `positive=false`
# path is exercised in the properties tier via the reciprocal identity.
EXP_INPUTS = [
    "0.0001", "0.001", "0.01", "0.1", "0.25", "0.5",
    "0.6931471805599453",   # ln(2): the range-reduction boundary r -> 0
    "0.6931471805599454",   # just past it
    "1", "1.5", "2", "2.718281828459045",
    "5", "10", "20", "30", "40", "50", "60",
    "61",                   # domain edge
]

# ln: domain is x > 0. Test below 1 (negative result), at 1, above 1,
# and around the m = 1.5 internal branch boundary.
LN_INPUTS = [
    "0.01", "0.1", "0.25", "0.5", "0.9", "0.99",
    "1.0000000001",
    "1.1", "1.25",
    "1.4999999999",         # just below the m=1.5 branch split
    "1.5",
    "1.5000000001",         # just above
    "1.75", "2", "2.718281828459045",
    "5", "10", "100", "1000", "1000000",
    "1000000000000",        # 1e12
]

# sqrt: domain is x >= 0. Perfect squares plus general values plus large.
SQRT_INPUTS = [
    "0.0001", "0.01", "0.25", "0.5", "1", "2", "3", "4",
    "9", "16", "100", "10000",
    "2.718281828459045",
    "1000000", "1000000000000",
]

# sin / cos: input is radians, any non-negative value (octant-reduced).
# Test each octant, the axes, and multi-revolution inputs.
TRIG_INPUTS = [
    "0.0001", "0.1",
    "0.7853981633974483",   # pi/4
    "1", "1.2",
    "1.5707963267948966",   # pi/2
    "2", "2.5",
    "3.141592653589793",    # pi
    "4", "4.5",
    "4.71238898038469",     # 3pi/2
    "5.5",
    "6.283185307179586",    # 2pi
    "7", "10",
    "12.566370614359172",   # 4pi (multi-revolution)
]


def emit_array(name, inputs, fn, signed_result=False):
    """Build a Solidity array literal for one function's vectors.

    Returns a list of source lines. Each vector is (input_wad, expected_wad)
    or (input_wad, expected_wad, negative_flag) when signed_result is set.
    """
    lines = []
    width = 3 if signed_result else 2
    lines.append(f"    // {name}: {len(inputs)} vectors, mpmath dps={mp.dps}")
    lines.append(f"    uint256[{width}][{len(inputs)}] internal {name};")
    lines.append("")
    return lines, [(s, fn(mpf(s))) for s in inputs]


def main():
    out = []
    out.append("// SPDX-License-Identifier: MIT")
    out.append("pragma solidity ^0.8.31;")
    out.append("")
    out.append("// AUTO-GENERATED by gen_vectors.py - do not edit by hand.")
    out.append(f"// Reference values computed with mpmath at {mp.dps}-digit precision.")
    out.append("// All values are 1e18-scaled (WAD). Regenerate when input sets change.")
    out.append("")
    out.append("contract TMathVectorData {")
    out.append("")

    # exp: result always positive over the tested domain.
    out.append(f"    // ---- exp: (exponentWad, expectedWad) ----")
    out.append(f"    uint256[2][{len(EXP_INPUTS)}] internal expVec;")
    exp_rows = []
    for s in EXP_INPUTS:
        x = mpf(s)
        ref = exp(x)
        exp_rows.append((to_wad(x), to_wad(ref)))
    out.append("    function _loadExp() internal {")
    for i, (inp, ref) in enumerate(exp_rows):
        out.append(f"        expVec[{i}] = [uint256({inp}), uint256({ref})];")
    out.append("    }")
    out.append("")

    # ln: result signed. Store (antilogWad, magnitudeWad, negativeFlag).
    out.append(f"    // ---- ln: (antilogWad, magnitudeWad, negative) ----")
    out.append(f"    uint256[3][{len(LN_INPUTS)}] internal lnVec;")
    ln_rows = []
    for s in LN_INPUTS:
        x = mpf(s)
        ref = log(x)
        neg = 1 if ref < 0 else 0
        ln_rows.append((to_wad(x), to_wad(abs(ref)), neg))
    out.append("    function _loadLn() internal {")
    for i, (inp, mag, neg) in enumerate(ln_rows):
        out.append(f"        lnVec[{i}] = [uint256({inp}), uint256({mag}), uint256({neg})];")
    out.append("    }")
    out.append("")

    # sqrt: result always positive.
    out.append(f"    // ---- sqrt: (xWad, expectedWad) ----")
    out.append(f"    uint256[2][{len(SQRT_INPUTS)}] internal sqrtVec;")
    sqrt_rows = []
    for s in SQRT_INPUTS:
        x = mpf(s)
        ref = sqrt(x)
        sqrt_rows.append((to_wad(x), to_wad(ref)))
    out.append("    function _loadSqrt() internal {")
    for i, (inp, ref) in enumerate(sqrt_rows):
        out.append(f"        sqrtVec[{i}] = [uint256({inp}), uint256({ref})];")
    out.append("    }")
    out.append("")

    # sin / cos: result signed. Store (xWad, magnitudeWad, negativeFlag).
    for fname, fn in (("sin", sin), ("cos", cos)):
        rows = []
        for s in TRIG_INPUTS:
            x = mpf(s)
            ref = fn(x)
            neg = 1 if ref < 0 else 0
            rows.append((to_wad(x), to_wad(abs(ref)), neg))
        out.append(f"    // ---- {fname}: (xWad, magnitudeWad, negative) ----")
        out.append(f"    uint256[3][{len(TRIG_INPUTS)}] internal {fname}Vec;")
        out.append(f"    function _load{fname.capitalize()}() internal {{")
        for i, (inp, mag, neg) in enumerate(rows):
            out.append(f"        {fname}Vec[{i}] = [uint256({inp}), uint256({mag}), uint256({neg})];")
        out.append("    }")
        out.append("")

    out.append("    function _loadAllVectors() internal {")
    out.append("        _loadExp();")
    out.append("        _loadLn();")
    out.append("        _loadSqrt();")
    out.append("        _loadSin();")
    out.append("        _loadCos();")
    out.append("    }")
    out.append("}")
    out.append("")

    src = "\n".join(out)
    with open("TMathVectors.gen.sol", "w") as f:
        f.write(src)

    # Console summary
    print(f"Generated TMathVectors.gen.sol")
    print(f"  exp:  {len(exp_rows)} vectors")
    print(f"  ln:   {len(ln_rows)} vectors")
    print(f"  sqrt: {len(sqrt_rows)} vectors")
    print(f"  sin:  {len(TRIG_INPUTS)} vectors")
    print(f"  cos:  {len(TRIG_INPUTS)} vectors")
    print(f"  total: {len(exp_rows)+len(ln_rows)+len(sqrt_rows)+2*len(TRIG_INPUTS)} vectors")


if __name__ == "__main__":
    main()
