#!/usr/bin/env python3
"""
gen_dalet_vectors.py - DaletOption.daml vectors from the funding bond reference.

Reads PERP/reference/fundingbond/vectors.json (the standard, computed by model.py at 60 digits)
and emits daml/DaletVectors.daml: every dalet_price vector, the p_atm vector (the put at
S = K = 1), the D vectors, and the vectors on which the pricer must return Left. The put
delta is carried as the magnitude of the model's dP/dS. Each expected
value is given at Numeric 18, floored and ceiled.

Run:  python3 scripts/gen_dalet_vectors.py [path/to/vectors.json]
Out:  daml/DaletVectors.daml  (committed; regenerate when vectors.json changes)

Standard library only. British English.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT = os.path.join(HERE, "..", "..", "..", "..", "PERP", "reference", "fundingbond",
                       "vectors.json")
OUT = os.path.join(HERE, "..", "daml", "DaletVectors.daml")

# The model prices edge/zero_scale (s = 1e-27); an 18-place implementation must refuse it.
LEFT = {"edge/zero_scale": "ZeroScale"}


def neg(x):
    """The negation of a fixed-point string."""
    return x[1:] if x.startswith("-") else ("-" + x if x.strip("0.") else x)


def lit(x):
    x = str(x)
    if "." not in x:
        x += ".0"
    return "(%s)" % x if x.startswith("-") else x


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else DEFAULT
    with open(src) as fh:
        doc = json.load(fh)
    prices, cdf, lefts = [], [], []
    for v in doc["vectors"]:
        vid = v["id"]
        if v["fn"] == "dalet_price":
            if vid in LEFT:
                lefts.append((vid, v["args"], LEFT[vid]))
                continue
            o = v["outputs"]
            fc = [o[k]["numeric18"][b] for k in ("call", "put", "delta_call") for b in ("floor", "ceil")]
            # the model's put delta is dP/dS (negative); daletPrice returns its magnitude
            fc += [neg(o["delta_put"]["numeric18"]["ceil"]), neg(o["delta_put"]["numeric18"]["floor"])]
            prices.append((vid, v["args"], fc, "True"))
        elif v["fn"] == "p_atm":
            sigma, h = v["args"]
            o = v["outputs"]["value"]["numeric18"]
            fc = [o["floor"], o["ceil"]] * 2 + ["0.0"] * 4
            prices.append((vid, ["1", "1", h, "0", sigma], fc, "False"))
        elif v["fn"] == "D":
            o = v["outputs"]["value"]["numeric18"]
            cdf.append((vid, v["args"][0], o["floor"], o["ceil"]))

    L = ["-- AUTO-GENERATED by scripts/gen_dalet_vectors.py - do not edit by hand.",
         "-- Source: PERP/reference/fundingbond/vectors.json (model.py, 60 digits).",
         "-- Expected values at Numeric 18, floor and ceiling of the exact value.",
         "",
         "module DaletVectors where",
         "",
         "data PriceVector = PriceVector",
         "  with",
         "    vid : Text",
         "    s : Numeric 18",
         "    k : Numeric 18",
         "    t : Numeric 18",
         "    r : Numeric 18",
         "    sigma : Numeric 18",
         "    callF : Numeric 18",
         "    callC : Numeric 18",
         "    putF : Numeric 18",
         "    putC : Numeric 18",
         "    dcF : Numeric 18",
         "    dcC : Numeric 18",
         "    dpF : Numeric 18",
         "    dpC : Numeric 18",
         "    checkDeltas : Bool",
         "",
         "data CdfVector = CdfVector",
         "  with",
         "    cid : Text",
         "    x : Numeric 18",
         "    lo : Numeric 18",
         "    hi : Numeric 18",
         "",
         "data LeftVector = LeftVector",
         "  with",
         "    lid : Text",
         "    ls : Numeric 18",
         "    lk : Numeric 18",
         "    lt : Numeric 18",
         "    lr : Numeric 18",
         "    lsigma : Numeric 18",
         "    reason : Text",
         "",
         "priceVectors : [PriceVector]",
         "priceVectors ="]
    for i, (vid, a, fc, chk) in enumerate(prices):
        L.append("  %s PriceVector \"%s\" %s %s %s"
                 % ("[" if i == 0 else ",", vid, " ".join(lit(x) for x in a),
                    " ".join(lit(x) for x in fc), chk))
    L.append("  ]")
    L.append("")
    L.append("cdfVectors : [CdfVector]")
    L.append("cdfVectors =")
    for i, (vid, x, f, c) in enumerate(cdf):
        L.append("  %s CdfVector \"%s\" %s %s %s" % ("[" if i == 0 else ",", vid, lit(x), lit(f), lit(c)))
    L.append("  ]")
    L.append("")
    L.append("leftVectors : [LeftVector]")
    L.append("leftVectors =")
    for i, (vid, a, why) in enumerate(lefts):
        L.append("  %s LeftVector \"%s\" %s \"%s\"" % ("[" if i == 0 else ",", vid,
                                                     " ".join(lit(x) for x in a), why))
    L.append("  ]")
    L.append("")
    with open(OUT, "w") as fh:
        fh.write("\n".join(L))
    print("%d price, %d cdf, %d left vectors -> %s" % (len(prices), len(cdf), len(lefts),
                                                       os.path.relpath(OUT)))


if __name__ == "__main__":
    main()
