#!/usr/bin/env python3
"""
gen_fundingbond_vectors.py - FundingBond.daml vectors from the funding bond reference.

Reads PERP/reference/fundingbond/vectors.json (the standard, computed by model.py at 60 digits)
and emits daml/FundingBondVectors.daml: every vector whose DAML counterpart is in
FundingBond.daml, with the floor and ceiling of its exact value at Numeric 18; the basis_settle
vectors entry by entry; the vectors on which FundingBond must return Left, with the reason. It
imports model.py for what vectors.json does not carry: the exact total paid in each basis_settle
vector, and the gap-claim grid of brief 2026-09-25b stage 3e (Strikes 0.02 to 50, floors and caps
a tenth to nine tenths away, sigma 0.8, h one hour).

Run:  python3 scripts/gen_fundingbond_vectors.py [path/to/vectors.json]
Out:  daml/FundingBondVectors.daml  (committed; regenerate when vectors.json changes)

Standard library only. British English.
"""
import json
import os
import sys
from decimal import ROUND_CEILING, ROUND_FLOOR, Decimal, localcontext

HERE = os.path.dirname(os.path.abspath(__file__))
FB = os.path.join(HERE, "..", "..", "..", "..", "PERP", "reference", "fundingbond")
DEFAULT = os.path.join(FB, "vectors.json")
OUT = os.path.join(HERE, "..", "daml", "FundingBondVectors.daml")

sys.path.insert(0, FB)
import model  # noqa: E402

# The reason FundingBond gives, as a substring of its Left.
LEFT = {"knock_in_long": "KnockedIn", "knock_in_short": "KnockedIn",
        "gap_claim_short": "ZeroCap", "gap_claim_long": "floor must not be negative"}

GRID_K = ("0.02", "0.05", "0.1", "0.2", "0.5", "0.9", "1", "1.1", "2", "5", "10", "20", "50")
GRID_F = ("0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9")
SIG = "0.8"
H = "0.000114155251141553"  # 3600 s of a 365-day year, 18 places (gen_vectors.years)


def n18(v, rounding):
    with localcontext() as c:
        c.prec = 200
        return format(Decimal(v).quantize(Decimal("1e-18"), rounding=rounding), "f")


def lit(x):
    x = str(x)
    if "." not in x:
        x += ".0"
    return "(%s)" % x if x.startswith("-") else x


def lst(xs):
    return "[%s]" % ", ".join(xs)


def book_args(book, U):
    """[U, K1, q1, K2, q2, ...], Strikes ascending, sizes aggregated per Strike."""
    agg = {}
    for q, K in book:
        agg[Decimal(K)] = agg.get(Decimal(K), Decimal(0)) + Decimal(q)
    out = [U]
    for K in sorted(agg):
        out += [str(K), str(agg[K])]
    return out


def ticks_args(perp, index):
    diff = Decimal(perp) - Decimal(index)
    dt = 1
    while diff * dt != (diff * dt).to_integral_value():
        dt *= 10
    return [str(int(diff * dt)), str(dt)]


def args_of(v):
    fn, a = v["fn"], v["args"]
    if fn in ("cap", "floor"):
        return book_args(a[0], a[1])
    if fn == "basis_log_ticks":
        return ticks_args(*a)
    return a


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else DEFAULT
    with open(src) as fh:
        doc = json.load(fh)
    vecs, settles, lefts = [], [], []
    for v in doc["vectors"]:
        if not v["counterpart"]["daml"].startswith("daml/Dalet-Soards/daml/FundingBond.daml"):
            continue
        vid, fn = v["id"], v["fn"]
        if "raises" in v:
            lefts.append((vid, fn, args_of(v), LEFT[fn]))
            continue
        if fn == "basis_settle":
            book, Ap, Ai, form = v["args"]
            out = model.basis_settle([tuple(e) for e in book], Ap, Ai, form)
            with localcontext() as c:
                c.prec = 200
                total = sum(-x for x in out if x < 0)
            rows = []
            for i, (side, q) in enumerate(book):
                key = ("pays_%d" if out[i] < 0 else "receives_%d") % i
                o = v["outputs"][key]["numeric18"]
                rows.append((side == "long", out[i] < 0, q, o["floor"], o["ceil"]))
            settles.append((vid, Ap, Ai, form == "ratio", rows, n18(total, ROUND_FLOOR)))
            continue
        o = v["outputs"]["paid" if fn == "ito_transfer" else "value"]
        vecs.append((vid, fn, args_of(v), o["numeric18"]["floor"], o["numeric18"]["ceil"]))

    grid = []
    for K in GRID_K:
        for f in GRID_F:
            with localcontext() as c:
                c.prec = 60
                fl = (Decimal(K) * (1 - Decimal(f))).quantize(Decimal("1e-18"))
                cp = (Decimal(K) * (1 + Decimal(f))).quantize(Decimal("1e-18"))
            grid.append((K, fl, True, n18(model.gap_claim_long(K, fl, SIG, H), ROUND_CEILING)))
            grid.append((K, cp, False, n18(model.gap_claim_short(K, cp, SIG, H), ROUND_CEILING)))

    L = ["-- AUTO-GENERATED by scripts/gen_fundingbond_vectors.py - do not edit by hand.",
         "-- Source: PERP/reference/fundingbond/vectors.json and model.py (60 digits).",
         "-- Numeric 18; lo and hi are the floor and ceiling of the exact value. args in",
         "-- FundingBond's order; cap and floor [U, K1, q1, K2, q2, ...], Strikes ascending;",
         "-- basis_log_ticks [dTickTime, dt]; ito_transfer lo/hi for paid and received alike.",
         "",
         "module FundingBondVectors where",
         "",
         "data FBVector = FBVector with vid : Text; fn : Text; args : [Numeric 18]; lo : Numeric 18; hi : Numeric 18",
         "",
         "data SettleVector = SettleVector with",
         "    sid : Text; ap : Numeric 18; ai : Numeric 18; ratio : Bool; isLong : [Bool]",
         "    pays : [Bool]; qs : [Numeric 18]; los : [Numeric 18]; his : [Numeric 18]",
         "    totalFloor : Numeric 18",
         "",
         "data FBLeftVector = FBLeftVector with lid : Text; lfn : Text; largs : [Numeric 18]; reason : Text",
         "",
         "data GridVector = GridVector with gk : Numeric 18; gx : Numeric 18; glong : Bool; gceil : Numeric 18",
         "",
         "sigmaGrid : Numeric 18",
         "sigmaGrid = %s" % SIG,
         "",
         "hGrid : Numeric 18",
         "hGrid = %s" % H,
         "",
         "fbVectors : [FBVector]",
         "fbVectors ="]
    for i, (vid, fn, a, lo, hi) in enumerate(vecs):
        L.append('  %s FBVector "%s" "%s" %s %s %s' % ("[" if i == 0 else ",", vid, fn,
                                                    lst(lit(x) for x in a), lit(lo), lit(hi)))
    L += ["  ]", "", "settleVectors : [SettleVector]", "settleVectors ="]
    for i, (vid, Ap, Ai, ratio, rows, tf) in enumerate(settles):
        col = lambda j: lst((str(r[j]) if isinstance(r[j], bool) else lit(r[j])) for r in rows)
        L.append('  %s SettleVector "%s" %s %s %s %s %s %s %s %s %s'
                 % ("[" if i == 0 else ",", vid, lit(Ap), lit(Ai), ratio, col(0), col(1), col(2),
                    col(3), col(4), lit(tf)))
    L += ["  ]", "", "leftVectors : [FBLeftVector]", "leftVectors ="]
    for i, (vid, fn, a, why) in enumerate(lefts):
        L.append('  %s FBLeftVector "%s" "%s" %s "%s"' % ("[" if i == 0 else ",", vid, fn,
                                                        lst(lit(x) for x in a), why))
    L += ["  ]", "", "-- | Stage 3e: gap claims at sigma 0.8, h one hour; ceiling of the model's value.",
          "gridVectors : [GridVector]", "gridVectors ="]
    for i, (K, X, lng, ce) in enumerate(grid):
        L.append("  %s GridVector %s %s %s %s" % ("[" if i == 0 else ",", lit(K), lit(X), lng, lit(ce)))
    L += ["  ]", ""]
    with open(OUT, "w") as fh:
        fh.write("\n".join(L))
    print("%d vectors (%d value, %d basis_settle, %d left), %d grid -> %s"
          % (len(vecs) + len(settles) + len(lefts), len(vecs), len(settles), len(lefts), len(grid),
             os.path.relpath(OUT)))


if __name__ == "__main__":
    main()
